
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABSTRACT ADD ADD_ASSIGN AND AND_ASSIGN ARROW ASSERT ASSIGN ATRATE BINARY_LIT BOOLEAN BOOL_LIT BREAK BYTE CASE CATCH CHAR CHAR_LIT CLASS COLON COLON_SEP COMMA COMMENT CONST CONTINUE DEC DECIMAL_LIT DEFAULT DO DOUBLE ELLIPSIS ELSE ENUM EQL EXTENDS FINAL FINALLY FLOAT FLOAT_DEC_LIT FLOAT_HEX_LIT FOR GEQ GOTO GTR HEX_LIT IDENT IF IMPLEMENTS IMPORT INC INSTANCEOF INT INTERFACE LAND LBRACE LBRACK LEQ LNOT LONG LOR LPAREN LSS MUL MUL_ASSIGN NATIVE NEQ NEW NOT NULL_LIT OCTAL_LIT OR OR_ASSIGN PACKAGE PERIOD PRIVATE PROTECTED PUBLIC QUES QUO QUO_ASSIGN RBRACE RBRACK REM REM_ASSIGN RETURN RPAREN SEMICOLON SHL SHL_ASSIGN SHORT SHR SHR_ASSIGN SHR_UN SHR_UN_ASSIGN STATIC STRICTFP STRING_LIT SUB SUB_ASSIGN SUPER SWITCH SYNCHRONIZED THIS THROW THROWS TRANSIENT TRY UNCLOSED_CHAR UNCLOSED_STR VOID VOLATILE WHILE XOR XOR_ASSIGNepsilon : '
    
_lr_action_items = {'$end':([0,1,],[-1,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'epsilon':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> epsilon","S'",1,None,None,None),
  ('epsilon -> <empty>','epsilon',0,'p_empty','parser.py',11),
]
